-- 코드를 입력하세요
SELECT SUBSTRING(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY SUBSTRING(PRODUCT_CODE, 1, 2)
-- 문자열 자르기는 SUBSTRING("문자열", 시작위치, 길이) 또는 LEFT("문자열", 길이) 또는 RIGHT("문자열", 길이)
ORDER BY CATEGORY;
