-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
EXCEPT
SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_INFO INFO JOIN ITEM_TREE TREE
ON INFO.ITEM_ID = TREE.PARENT_ITEM_ID
ORDER BY ITEM_ID DESC;
