SELECT PRO.PRODUCT_ID, PRO.PRODUCT_NAME, SUM(ORD.AMOUNT*PRO.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT PRO JOIN FOOD_ORDER ORD
ON PRO.PRODUCT_ID = ORD.PRODUCT_ID
WHERE TO_CHAR(ORD.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
-- GROUP BY절에 PRODUCT_ID말고도 PRO.PRODUCT_NAME를 추가해야 함.
-- SELECT에서 사용된 컬럼 중 집계 함수에 사용되는 컬럼 제외하고 모든 칼럼이 GROUP BY절에 있어야 함.
GROUP BY PRO.PRODUCT_ID, PRO.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
